# Generated by Django 6.0.7 on 2026-08-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.TextField(max_length=120, verbose_name='Короткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('date', models.DateField(verbose_name='Дата добавления')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('author', models.CharField(verbose_name='Автор')),
                ('category', models.CharField(choices=[('Бытовая техника', 'Бытовая техника'), ('Смартфоны', 'Смартфоны'), ('Ноутбуки и ПК', 'Ноутбуки и ПК'), ('Другое', 'Другое')], default='Другое', verbose_name='Категория')),
                ('brand', models.CharField(choices=[('Asus', 'Asus'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('Другое', 'Другое')], default='Другое', verbose_name='Бренд')),
                ('condition', models.CharField(choices=[('Новое', 'Новое'), ('Б/У', 'Б/У')], default='Новое', verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
