# Generated by Django 6.0.7 on 2026-08-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(choices=[('LG', 'LG'), ('Dell', 'Dell'), ('Asus', 'Asus'), ('Lenovo', 'Lenovo'), ('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('Другое', 'Другое')], default='Другое', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=22, verbose_name='Название'),
        ),
    ]
