# Generated by Django 6.0.7 on 2026-08-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_alter_products_brand_alter_products_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(choices=[('LG', 'LG'), ('Dell', 'Dell'), ('Poco', 'Poco'), ('Asus', 'Asus'), ('Lenovo', 'Lenovo'), ('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('Другое', 'Другое')], default='Другое', verbose_name='Бренд'),
        ),
    ]
