# Generated by Django 6.0.7 on 2026-08-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_alter_products_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(choices=[('LG', 'LG'), ('Dell', 'Dell'), ('Asus', 'Asus'), ('Sony', 'Sony'), ('Steam', 'Steam'), ('Apple', 'Apple'), ('Honor', 'Honor'), ('Huawei', 'Huawei'), ('Lenovo', 'Lenovo'), ('Xiaomi', 'Xiaomi'), ('Samsung', 'Samsung'), ('Infinix', 'Infinix'), ('Microsoft', 'Microsoft'), ('Другое', 'Другое')], default='Другое', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Консоли', 'Консоли'), ('Смартфоны', 'Смартфоны'), ('Ноутбуки и ПК', 'Ноутбуки и ПК'), ('Бытовая техника', 'Бытовая техника'), ('Другое', 'Другое')], default='Другое', verbose_name='Категория'),
        ),
    ]
