# Generated by Django 6.0.7 on 2026-08-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_alter_products_brand_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(choices=[('LG', 'LG'), ('Dell', 'Dell'), ('Asus', 'Asus'), ('Sony', 'Sony'), ('Steam', 'Steam'), ('Apple', 'Apple'), ('Honor', 'Honor'), ('Huawei', 'Huawei'), ('Lenovo', 'Lenovo'), ('Xiaomi', 'Xiaomi'), ('Samsung', 'Samsung'), ('Infinix', 'Infinix'), ('Microsoft', 'Microsoft'), ('Other', 'Другое')], default='Other', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Консоли', 'Консоли'), ('Смартфоны', 'Смартфоны'), ('Ноутбуки и ПК', 'Ноутбуки и ПК'), ('Бытовая техника', 'Бытовая техника'), ('Other', 'Другое')], default='Other', verbose_name='Категория'),
        ),
    ]
