# Generated by Django 6.0.7 on 2026-08-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0006_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Consoles', 'Консоли'), ('Phones', 'Смартфоны'), ('Laptops and PC', 'Ноутбуки и ПК'), ('Household', 'Бытовая техника'), ('Other', 'Другое')], default='Other', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='condition',
            field=models.CharField(choices=[('Used', 'Б/У'), ('New', 'Новое')], default='New', verbose_name='Состояние'),
        ),
    ]
