# Generated by Django 6.0.7 on 2026-08-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0007_alter_products_category_alter_products_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(choices=[('LG', 'LG'), ('Dell', 'Dell'), ('Asus', 'Asus'), ('Sony', 'Sony'), ('Steam', 'Steam'), ('Apple', 'Apple'), ('Honor', 'Honor'), ('Huawei', 'Huawei'), ('Lenovo', 'Lenovo'), ('Xiaomi', 'Xiaomi'), ('Samsung', 'Samsung'), ('Infinix', 'Infinix'), ('Nintendo', 'Nintendo'), ('Microsoft', 'Microsoft'), ('Other', 'Другое')], default='Other', verbose_name='Бренд'),
        ),
    ]
