# Generated by Django 6.0.7 on 2026-08-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0009_alter_products_brand_alter_products_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='model',
            field=models.CharField(default=1, max_length=30, verbose_name='Модель'),
            preserve_default=False,
        ),
    ]
