# Generated by Django 6.0.7 on 2026-08-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0015_alter_products_brand_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='products/default_images', verbose_name='Изображение'),
        ),
    ]
