# Generated by Django 6.0.7 on 2026-08-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0016_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='condition',
            field=models.CharField(choices=[('Б-У', 'Б/У'), ('Новое', 'Новое')], default='Новое', verbose_name='Состояние'),
        ),
    ]
