# Generated by Django 6.1 on 2026-08-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0017_alter_products_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ubdate_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=120, verbose_name='Короткое описание'),
        ),
    ]
