# Generated by Django 6.1 on 2026-09-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0019_alter_products_options_brand_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='просмотры'),
        ),
    ]
