# Generated by Django 6.1 on 2026-09-11 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0020_products_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='products_app.products', verbose_name='Продукт'),
        ),
        migrations.CreateModel(
            name='ShareLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('ubdate_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Whatsapp')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='products_app.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
