# Generated by Django 6.1 on 2026-09-11 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0021_alter_products_options_alter_imagegallery_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('ubdate_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Whatsapp')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='products_app.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='ShareLinks',
        ),
    ]
